// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BancoAPI.Models
{
    public partial class Clientes
    {
        [Key]
        public int Id { get; set; }
        [StringLength(60)]
        public string Nome { get; set; }
        [StringLength(40)]
        public string Documento { get; set; }
        [StringLength(40)]
        public string ChaveOrigem { get; set; }
        public double? Saldo { get; set; }

        [InverseProperty("FkClienteNavigation")]
        public virtual ICollection<TbTransacoes> TbTransacoes { get; set; }
    }
}